### PR TITLE
Fix panics. Fix computation of median lifetimes in activity report.

### PR DESCRIPTION
**Pull request by rgooch**

### CODE REVIEW

**Comment by cviecco** [comment]
LGTM. Will merge once test pass. (Had to restart Darwin)

**Comment by rgooch** [comment]
It's server-side only. We don't care about anything but Linux :-)

**Comment by cviecco** [comment]
Something that was recently added to the dominator library is linux specific ..
/Dominator/lib/net/bind.go:234: undefined: syscall.TCP_KEEPINTVL

../Dominator/lib/net/bind.go:239: undefined: syscall.TCP_KEEPIDLE

../Dominator/lib/net/bind.go:244: undefined: syscall.TCP_KEEPCNT

Need to make dominator net cross platform or remove this dependency

**Comment by rgooch** [comment]
Yeah, I just noticed that. Will fix...

**Comment by rgooch** [comment]
Fix pushed to Dominator. Build pending...
BTW: we can't remove that dependency since the logger depends on lib/srpc which depends on lib/net :-)

**Comment by rgooch** [comment]
Build is fixed!

**Pull request merged**
